version: '3.8'

services:
  phappgateway:
    image: phappgateway:latest
    build:
      context: .
      dockerfile: PhAppGateway/Dockerfile
    ports:
      - "5000:80" # Mapea el puerto 80 del contenedor al puerto 5000 en tu máquina local
      - "5001:443" # Mapea el puerto 443 del contenedor al puerto 5001 en tu máquina local
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE=ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
    depends_on:
      - phappsecurity
      - phappuser

  phappsecurity:
    image: phappsecurity:latest
    build:
      context: .
      dockerfile: PhAppSecurity/Dockerfile

    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}

  phappuser:
    image: phappuser:latest
    build:
      context: .
      dockerfile: PhAppUser/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql

volumes:
  dbdata:
